import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../../componets/Navbar';
import catIndex from '../../public/img/catIndex.png';
/*PARA IMAGENES DE CONTAINER 3*/
import categories_1 from '../../public/img/categories_1.png';
import categories_2 from '../../public/img/categories_2.png';
import categories_3 from '../../public/img/categories_3.png';
import categories_4 from '../../public/img/categories_4.png';
import categories_5 from '../../public/img/categories_5.png';



const inter = Inter({ subsets: ['latin'] })
import { useState, useEffect } from 'react';

export default function Home() {

  const [product, setProduct] = useState([
    {
      id: "",
      nombre: "",
      descripcion: "",
      precio: "",
    },
  ]);

  useEffect(() => {
    localStorage.getItem("product") && setProduct(JSON.parse(localStorage.getItem("product")));
  }, []);




  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar page={1} numCarrito={product.length} />
        <div className='sectionOne'>
          <div className='sectionOneContainerTwo'>
            <center>
              <h1 style={{ fontSize: "40px" }}>Bienvenido a nuestra petshop, donde encontrarás todo lo que necesitas para cuidar y consentir a tu mascota</h1>
            </center>
          </div>

        </div>
        <div className='sectionTwo'>
          <div className='sectionTwoCOntent'>
            <div >
              <Image src={catIndex} />
            </div>
            <div style={{ width: "50%", marginRight: "50px" }}>
              <h1 style={{ fontSize: "40px", color: "white" }}>¿Por qué comprar en nuestra petshop?</h1>

              <center>
                <h3 style={{ marginTop: "100px", fontSize: "28px", fontWeight: "300" }}>
                  Nuestro petshop es una tienda en línea que ofrece una amplia variedad de productos para mascotas, desde alimentos hasta juguetes y accesorios. Nos enfocamos en brindar productos de alta calidad y satisfacer las necesidades de tus amigos peludos, todo con la comodidad de recibirlos en la puerta de tu casa.
                </h3>
              </center>

            </div>
          </div>

        </div>

        <div className='sectionTwo'>
          <div className='sectionThreeContent'>
            <div >
              <Image src={categories_1} />
            </div>
            <div >
              <Image src={categories_2} />
            </div>
            <div >
              <Image src={categories_3} />
            </div>
            <div >
              <Image src={categories_4} />
            </div>
            <div >
              <Image src={categories_5} />
            </div>


          </div>
          <div style={{ color: "white", width:"100%"}}>
            <center>
              <br /><br /><br /><br /><br />
              <h1>
                Nuestras Categorías de Productos
              </h1>
              <h3 style={{ marginTop: "50px", fontSize: "28px", fontWeight: "300", width:"50%" }}>
              En nuestra tienda de mascotas ofrecemos productos de alta calidad para perros, gatos, aves, hamsters y peces. Desde alimentos, juguetes y accesorios, hasta artículos de higiene y cuidado personal, contamos con todo lo necesario para satisfacer las necesidades de cada mascota y su dueño. Nuestros productos son seleccionados cuidadosamente para brindar el mejor cuidado y bienestar para tu compañero peludo o emplumado.</h3>
            </center>


          </div>

        </div>
      </main>
    </>
  )
}
