import Head from 'next/head'
import AwesomeSlider from 'react-awesome-slider';
import withAutoplay from 'react-awesome-slider/dist/autoplay';

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'react-awesome-slider/dist/styles.css';
import Navbar from '../../componets/Navbar';
import Image from 'next/image';
import dog from '../../public/img/dog.png';
import cat from '../../public/img/cat.png';
import loro from '../../public/img/loro.png';
import hamster from '../../public/img/hamster.png';
import pez from '../../public/img/pez.png';
import { getData } from "../../controllers/ProductController"
import { useEffect, useState } from 'react';

import {FaDog, FaCat} from 'react-icons/fa'; 
import { GiEgyptianBird, GiSeatedMouse,GiCirclingFish} from 'react-icons/gi'; 
import {BiCategoryAlt }  from 'react-icons/bi';
import {MdSell} from 'react-icons/md';
const AutoplaySlider = withAutoplay(AwesomeSlider);


export default function productos({ }) {

    const [data, setData] = useState([]);

    //quiero un useState para guardar el producto que se va a comprar como lista

    const [product, setProduct] = useState([]);

    useEffect(() => {
        getData().then((res) => {
            setData(res);
        });

        const storedProduct = localStorage.getItem("product");
        if (storedProduct) {
            const parsedProduct = JSON.parse(storedProduct);
            if (parsedProduct.length) {
                setProduct(parsedProduct);
            }
        }
    }, []);

    useEffect(() => {
        localStorage.setItem("product", JSON.stringify(product));
        console.log(product);
    }, [product]);


    const notifyComprar = () => toast("Producto añadido al carrito!");

    const handlerComprarProducto = (id, nombre, descripcion, precio) => {
        setProduct([
            ...product,
            {
                id: id,
                nombre: nombre,
                descripcion: descripcion,
                precio: precio,
            },
        ]);
        notifyComprar();
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <div>
                    <ToastContainer />
                </div>

                <Navbar page={2} numCarrito={product.length} />
                <div className='productSectionOne'>

                    <AutoplaySlider
                        play={true}
                        cancelOnInteraction={false} // should stop playing on user interaction
                        interval={4000}
                        style={{ height: '87%', zIndex: '-1' }}
                    >

                        <div data-src="/img/image1.png" ></div>
                        <div data-src="/img/image2.png" ></div>
                        <div data-src="/img/image3.png" ></div>
                        <div data-src="/img/image4.png" ></div>
                    </AutoplaySlider>
                    <div style={{ marginTop: "50px" }}>
                        <h1><BiCategoryAlt/>Categorias</h1>
                    </div>
                    <div className='gridBox' style={{marginTop: "80px"}}>
                        <div className='item' >

                            <h3>Perros</h3>
                            <Image src={dog} alt="Picture of the author" />
                            <a href="#perros">ir</a>

                        </div>
                        <div className='item' >
                            <h3>Gatos</h3>
                            <Image src={cat} alt="Picture of the author" />
                            <a href="#gatos">ir</a>
                        </div>
                        <div className='item' >
                            <h3>Aves</h3>
                            <Image src={loro} alt="Picture of the author" />
                            <a href="#aves">ir</a>
                        </div>
                        <div className='item' >
                            <h3>Hamnsters</h3>
                            <Image src={hamster} alt="Picture of the author" />
                            <a href="#hamnsters">ir</a>
                        </div>
                        <div className='item' >
                            <h3>Peces</h3>
                            <Image src={pez} alt="Picture of the author" />
                            <a href="#peces">ir</a>
                        </div>


                    </div>
                    <div style={{marginTop:"70px"}}>
                        <center>
                            <h2>
                                ¡Bienvenido a nuestra tienda de mascotas! Aquí en nuestra sección de categorías, ofrecemos una amplia variedad de productos para asegurarnos de que todos los dueños de mascotas encuentren lo que están buscando para sus amigos peludos, emplumados o escamosos.
                            </h2>
                        </center>
                        <br />
                        <br />


                    </div>
                        <div style={{ marginTop: "70px" }}>
                            <div>
                                <h1><MdSell/>Productos</h1>
                            </div>
                            <div>
                                <h3>En esta sección encontrarás todos los productos que tenemos para ti, desde los más básicos hasta los más sofisticados, para que puedas elegir el que más se adapte a tus necesidades.</h3>
                            </div>
                        </div>


                    <div className='gridBoxContainer' style={{marginTop:"50px"}}>
                        <h2 id='perros'><  FaDog style={{color:"#a50239"}}/>Categoría Perros</h2>
                        <div className='gridBox'>
                            {data.filter((item) => item.category === 'Perros').map((item) => (
                                <div className='item' key={item.id}>
                                    <h3>{item.nombre}</h3>
                                    <p>{item.escripcion}</p>
                                    <p>${item.precio}</p>
                                    <button onClick={() => handlerComprarProducto(item.id, item.nombre, item.escripcion, item.precio)}>Comprar!</button>
                                </div>
                            ))}
                        </div>
                        <h2 id='gatos'><FaCat style={{color:"#a50239"}}/>Categoría Gatos</h2>
                        <div className='gridBox'>
                            {data.filter((item) => item.category === 'Gatos').map((item) => (
                                <div className='item' key={item.id}>
                                    <h3>{item.nombre}</h3>
                                    <p>{item.escripcion}</p>
                                    <p>${item.precio}</p>
                                    <button onClick={() => handlerComprarProducto(item.id, item.nombre, item.escripcion, item.precio)}>Comprar!</button>
                                </div>
                            ))}
                        </div>

                        <h2 id='aves'><GiEgyptianBird style={{color:"#a50239"}}/>Categoría Aves</h2>
                        <div className='gridBox'>
                            {data.filter((item) => item.category === 'Aves').map((item) => (
                                <div className='item' key={item.id}>
                                    <h3>{item.nombre}</h3>
                                    <p>{item.escripcion}</p>
                                    <p>${item.precio}</p>
                                    <button onClick={() => handlerComprarProducto(item.id, item.nombre, item.escripcion, item.precio)}>Comprar!</button>
                                </div>
                            ))}
                        </div>
                        <h2 id='hamnsters'><GiSeatedMouse style={{color:"#a50239"}}/>Categoría Hamnsters</h2>
                        <div className='gridBox'>
                            {data.filter((item) => item.category === 'Hamsters').map((item) => (
                                <div className='item' key={item.id}>
                                    <h3>{item.nombre}</h3>
                                    <p>{item.escripcion}</p>
                                    <p>${item.precio}</p>
                                    <button onClick={() => handlerComprarProducto(item.id, item.nombre, item.escripcion, item.precio)}>Comprar!</button>
                                </div>
                            ))}
                        </div>

                        <h2 id='peces'><GiCirclingFish style={{color:"#a50239"}}/>Categoría Peces</h2>
                        <div className='gridBox'>
                            {data.filter((item) => item.category === 'Peces').map((item) => (
                                <div className='item' key={item.id}>
                                    <h3>{item.nombre}</h3>
                                    <p>{item.escripcion}</p>
                                    <p>${item.precio}</p>
                                    <button onClick={() => handlerComprarProducto(item.id, item.nombre, item.escripcion, item.precio)}>Comprar!</button>
                                </div>
                            ))}
                        </div>
                    </div>


                </div>
            </main>
        </>
    )
}
