import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '../../componets/navbar';

import { GetServerSideProps } from 'next';

interface productsProps {
    data: {
        id: number,
        nombre: string,
        escripcion: string,
        precio: number,
    }[];
}


export default function productos({ data }: productsProps) {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Navbar page={2} />
                <div className='productSectionOne'>
                    <div>
                        <h1>Productos</h1>
                    </div>
                    <div>
                        <p>En esta sección encontrarás todos los productos que tenemos para ti, desde los más básicos hasta los más sofisticados, para que puedas elegir el que más se adapte a tus necesidades.</p>
                    </div>
                    <div className='gridBox'>

                        {data.map((item) => (
                            <div className='item' key={item.id}>
                                <h3>{item.nombre}</h3>
                                <p>{item.escripcion}</p>
                                <p>{item.precio}</p>
                            </div>
                        ))
                        }
                    </div>

                </div>
            </main>
        </>
    )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const res = await fetch('http://localhost:5086/api/Products')
    const data = await res.json()
    return {
        props: { data }
    }
}